// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyohwhsqfjbspvvxfwah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5b2h3aHNxZmpic3B2dnhmd2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0MDc1ODQsImV4cCI6MjA1MTk4MzU4NH0.Sxyj6bxptiy1uVRnDc5OHZoxOA1DFWf3Gz5Fabbhwmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);